version: '1'

services:
rclone:
    image: rclone/rclone
    restart: always
    env_file:
      - ./rclone.env
    ports:
      - "80:80"
      - "8080:8080"
    networks:
      - x11
networks:
  x11:

    
