version: '1'

services:
rclone:
    image: rclone/rclone:latest
    restart: always
    env_file:
      - ./rclone.env
    ports:
      - "80:80"
      - "8000:8000"
    networks:
      - x11
networks:
  x11:

    
